### PR TITLE
Adding api

### PR DESCRIPTION
**Pull request by nunogoncalves**
Hi!
This pull request adds an api to github awards. It includes three endpoints:
api/v0/users and api/v0/users/search and /api/v0/languages

The index returns a json object like so:
```json
{
  "users": [
    {
      "id": 3430, 
      "login": "nunogoncalves", 
      "gravatar_url": "url", 
      "city": "lisbon", 
      "country": "portugal", 
      "city_rank": 1, 
      "country_rank": 1, 
      "world_rank": 1
    }
  ]
}
````
And the search endpoint:
```json
{
  "user": {
    "id": 3446,
    "login": "nunogoncalves",
    "gravatar_url": "url",
    "city": "lisbon",
    "country": "portugal",
    "rankings": [
    {
      "language": "swift",
      "repository_count": 2,
      "stars_count": 0,
      "city": "lisbon",
      "city_rank": 1,
      "country": "portugal",
      "country_rank": 1,
      "world_rank": 1
    }, {
      "language": "ruby",
       "repository_count": 1,
       "stars_count": 0,
       "city": "lisbon",
       "city_rank": 1,
       "country": "portugal",
       "country_rank": 1,
       "world_rank": 1
    }]
  }
}
```
The Languages endpoint will return an object with languages as a root object and an array with available languages.

```json
{ 
   "languages": ["Ruby", "Java", "Swift"] 
}
```

I added new dependencies. pry-byebug in order to be able to make binding.pry and navigate in breakpoints during dev, and active-models-serializer to easily create the endpoint's responses.

Hope I didn't forget anything important and you like the adition.
Let me know if you like it and if you don't, tell me what to fix/add.

### CODE REVIEW

**Comment by vdaubry** [comment]
That's awesome ! I'm sure a lot of people are going to benefit from this.

Let me just take some time to review this, i'll tell you if we need to adapt some stuff.

**Comment by nunogoncalves** [comment]
:) 
I'm also still thinking about it. Maybe the response should also include the search context.

**Comment by nunogoncalves** [comment]
@vdaubry could you add the vcr cassets to version control? running tests locally fails when they depend on recordings. Anyway, since I'm not changing any behaviour I'm just testing my own code.

**Comment by vdaubry** [comment]
I've reviewed  the code, this is really good stuff !

There's some things i'd like to do before we merge this. Here is a list ordered by priority :

- Provide documentation, i was thinking of using [apipie-rails](https://github.com/Apipie/apipie-rails) . That will also allow us to advertise about this work :
	- http://www.programmableweb.com/
	- http://apis.io/
	- Hacker News

- Params should be case insensitive :

Even if we provide a languages list endpoint, the API should not be case sensitive. This is something i wanted to do for some time, i need to re-compute rankings so that redis keys are all downcase. I'm taking care of this.

For example, if you search for ```ruby ``` instead of ``` Ruby ```:
``` api/v0/users?type=city&city=paris&language=ruby ```


- Don't return default values for the user index endpoint :

Currently the ``` UserListPresenter ```returns default values when it cannot find the corresponding keys in redis. This was ok for the web interface but it's a problem for the API.

Example :
``` api/v0/users?city=France&language=Ruby ```
=> Returns San Francisco rankings.


- Simplify params for the User index endpoint :

``` api/v0/users?type=city&city=Paris&language=Ruby ```

The city parameter is redundant. This comes from the ``` UserListPresenter ```, we should refactor this class so you could only send a ``` city ``` or ``` country ``` param and it would figure out what you mean without providing the ``` type ``` param

This endpoint would be easier to use :
``` api/v0/users?city=Paris&language=Ruby ```
``` api/v0/users?country=France&language=Ruby ```


Once we've done that i think we don't need to return informations about the ``` location_type ``` , ``` location_name ``` and ``` language ``` , we could remove the   ``` Api::V0::UsersController#filter_context ```  ?



- Validate user params for the user index endpoint :

We should return an error code when we cannot find a language or location :

For example :
``` api/v0/users?country=Paris&language=Ruby ```
``` api/v0/users?city=Paris&language=J2EE ```

When we cannot fullfill a request with the given parameters we should return an [error object](http://jsonapi.org/format/#error-objects) and return a 400 status code


- Dry the language list endpoint :

Create a service object for languages, put the ``` read_languages_from_file ```
into a ``` LanguageList class ```


- Change the route for User search endpoint ? : 

``` api/v0/users/search?login=nunogoncalves ```

Instead of a search action we could just GET a user ressource :
``` /api/v0/users/nunogoncalves ```

What's your opinion about that ?

--

This might seem a lot but most of these items are really quick wins. I'll have some time to work on this in the next days, let me know if you want to take care of some of these items.

Thanks again for your work, this is good code !

**Comment by nunogoncalves** [comment]
Hi! Thanks! I'm glad you liked the PR. :) Here's my thoughts on what you said:

---
>Provide documentation, i was thinking of using apipie-rails . That will also allow us to advertise about this work :
>
>http://www.programmableweb.com/
>http://apis.io/
>Hacker News

I didn't know apipie-rails. Would also suggest a quick look at [Swagger](http://swagger.io/) which I have used in the past. It also provides a nice interface to document and interact with the api. :) There's a [rails gem](https://github.com/richhollis/swagger-docs) to build the docs and the ui is provided by [Swagger-ui](https://github.com/swagger-api/swagger-ui)

I made a small example when I was starting to using it a while ago (probably very outdated) [here](https://github.com/nunogoncalves/SwagDogsApi)

---
For some of the few next issues you pointed, before commenting on each one I would just like to point that I didn't want to introduce any extra logic to what was already done. Hence I just called most of your classes. Of course It's not the best thing to do to be using presenters for html and api, but it was the fastest and cleanest way of creating the API without adding too much new stuff and probably duplication. Besides, some of your tests were failing on my local machine (I should really read the read me all the way through :P) so I didn't want to go touching muddy grounds :D
I guess there's a good opportunity for some refactors now. 

---
>Params should be case insensitive :

>Even if we provide a language list endpoint, the API should not be case sensitive. This is something i wanted to do for some time, i need to re-compute rankings so that redis keys are all downcase. I'm taking care of this.

>For example, if you search for ruby instead of Ruby:
>api/v0/users?type=city&city=paris&language=ruby

:+1: I agree.
I would also suggest the following: Looks that you are displaying more common languages first (probably based used on something like [githut](http://githut.info)?). I think it could be interesting to separate them in the api response so the client could use that information if he wants to. He could just merge both arrays, or use them separately. 

---
>Don't return default values for the user index endpoint :
>Currently the UserListPresenterreturns default values when it cannot find the corresponding keys in params. This was ok for the web interface but it's a problem for the API.

>Example :
>api/v0/users?city=France&language=Ruby
>=> Returns San Francisco rankings.

I agree with this as well. 
But I don't really know what the api should respond with when the call doesn't provide enough params... If the client calls: *api/v0/users* what should be returned? Empty list? 400? What about return the absolute world ranking? Disregarding location and language? Could be interesting.

---
>Simplify params for the User index endpoint :
>api/v0/users?type=city&city=Paris&language=Ruby

>The city parameter is redundant. This comes from the UserListPresenter, we should refactor this class so you could only send a city or country param and it would figure out what you mean without providing the type param

>This endpoint would be easier to use :
>api/v0/users?city=Paris&language=Ruby
>api/v0/users?country=France&language=Ruby

>Once we've done that i think we don't need to return informations about the location_type , location_name and language , we could remove the Api::V0::UsersController#filter_context ?

Yap, this makes total sense. :) If neither of the params are present, we can either return an empty list or world rankings. I guess the latter is nice. :) 

---
>Validate user params for the user index endpoint :
>We should return an error code when we cannot find a language or location :

>For example :
>api/v0/users?country=Paris&language=Ruby
>api/v0/users?city=Paris&language=J2EE

>When we cannot fullfill a request with the given parameters we should return an error object and return a 400 status code

The city/country way of dealing with this might be tricky. Do you really want to have to deal with this? I mean, should the api return an error when a client searches for "Lisboa" instead of "Lisbon"? Maybe a 200 and an empty list is more suitable to avoid tangling ourselves with location issues.

---
>Dry the language list endpoint :
>Create a service object for languages, put the read_languages_from_file
into a LanguageList class

Yes, I should have done that. :) 

---
>Change the route for User search endpoint ? :
>api/v0/users/search?login=nunogoncalves

>Instead of a search action we could just GET a user ressource :
>/api/v0/users/nunogoncalves

>What's your opinion about that ?

I like it. Makes perfect sense and it's "resti". It's easy to return a 200 or a 400. 
In adition I would suggest adding a login_cont parameter to the users index endpoint. This way we can provide a real search mechanism. :) [Ransack](https://github.com/activerecord-hackery/ransack/) is perfect for this.
/api/v0/users?login_cont=nuno -> all users starting with nuno would be returned. This is perfect for searching by names 

---
>This might seem a lot but most of these items are really quick wins. I'll have some time to work on this in >the next days, let me know if you want to take care of some of these items.

>Thanks again for your work, this is good code !

Thanks. :) 
I can start on the most straightforward ones. Like the index/show endpoints. We should keep talking to discuss things. :)

**Comment by nunogoncalves** [comment]
Hi @vdaubry check my branch swagger-docs
https://github.com/nunogoncalves/github-awards/tree/swagger-docs. It's still WIP but let me know if you like what you see. 

Just run the server on port 2000 (it's still hardcoded) and then go to http://localhost:2000/docs

**Comment by vdaubry** [comment]
hi @nunogoncalves, i just had a look at your swagger-docs branch, it looks great !
You can merge this into your master branch.

Regarding your other comments :

- Language list :
You're right, we should return a list of languages ordered alphabetically. And maybe add an option to sort them by popularity. Anyway returning a list ordered alphabetically as a first step seems good.

- Don't return default values for the user index endpoint :
Great idea ! Without any params we return the absolute world ranking

- Validate user params for the user index endpoint :
Ok, let's return "200" + empty list when we can't answer with the provided params.

- Regarding the user search API :
For the 1st release of the API i think it's more safe to only provide a GET /users/{login} route
=> We do a simple find in database, we're sure it will always be fast.

Before adding search functionnality we need to do some performance benchmark : there are more than 12M rows in the user table, and i would like all endpoints to respond in less than 100ms for any possible query.
Maybe we can do that in the next release of the API ?

**Comment by vdaubry** [comment]
I have some changes to commit, i'm creating a branch for the API : #90

Can you push your modifications against this branch ?

**Pull request closed without merging**
